name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '30 12 * * 1-5'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ZjBlog/message@v1.5
        env: 
          MESSAGE: "小主记得填打开填工时哈~~"
          URL: ${{ secrets.URL }}  
