# This is a basic workflow to help you get started with Actions

name: perday

on:
  schedule:
  - cron: "5 * * * 1-5"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - name: send-message
      uses: ZjBlog/message@v1.5
      env: 
        MESSAGE: "小主记得填打开填工时哈~~"
        URL: ${{ secrets.URL }}  
