name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 11-13 20 * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ZjBlog/message@v1.5
        env: 
          MESSAGE: "小主记得申请当月的加班时间"
          URL: ${{ secrets.URL }}  
